name: build

on:
  push:
    branches:
      # long-lived branches
      - master

  pull_request:
    branches:
      - "*"

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node-version: [16.x]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: npm lint:sol
      run: npm run lint:sol

    - name: npm build
      run: npm run build

    - name: npm test
      run: npm run test
